# Generated by Django 3.2.16 on 2023-01-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllBlogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_name',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='Images'),
        ),
    ]
